<?php /** @var \App\Application $this */ ?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?= $this->getTitle(); ?></title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
</head>
<body class="blog-body">
    <div class="container">
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-12">
                    <?= $this->getContent(); ?>
                </div>
            </div>
        </main>
    </div>
</body>
</html>
